/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExteriorRouteImport } from './routes/exterior'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InteriorRouteImport } from './routes/interior'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProRouteImport } from './routes/pro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExteriorRoute = ExteriorRouteImport.update({
  id: '/exterior',
  path: '/exterior',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRoute = InteriorRouteImport.update({
  id: '/interior',
  path: '/interior',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exterior': typeof ExteriorRoute
  '/faq': typeof FaqRoute
  '/interior': typeof InteriorRoute
  '/pricing': typeof PricingRoute
  '/pro': typeof ProRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exterior': typeof ExteriorRoute
  '/faq': typeof FaqRoute
  '/interior': typeof InteriorRoute
  '/pricing': typeof PricingRoute
  '/pro': typeof ProRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exterior': typeof ExteriorRoute
  '/faq': typeof FaqRoute
  '/interior': typeof InteriorRoute
  '/pricing': typeof PricingRoute
  '/pro': typeof ProRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/exterior' | '/faq' | '/interior' | '/pricing' | '/pro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/exterior' | '/faq' | '/interior' | '/pricing' | '/pro'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/exterior'
    | '/faq'
    | '/interior'
    | '/pricing'
    | '/pro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExteriorRoute: typeof ExteriorRoute
  FaqRoute: typeof FaqRoute
  InteriorRoute: typeof InteriorRoute
  PricingRoute: typeof PricingRoute
  ProRoute: typeof ProRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exterior': {
      id: '/exterior'
      path: '/exterior'
      fullPath: '/exterior'
      preLoaderRoute: typeof ExteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior': {
      id: '/interior'
      path: '/interior'
      fullPath: '/interior'
      preLoaderRoute: typeof InteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExteriorRoute: ExteriorRoute,
  FaqRoute: FaqRoute,
  InteriorRoute: InteriorRoute,
  PricingRoute: PricingRoute,
  ProRoute: ProRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
